### ISSUE TITLE
添加 Overleaf 支持

### ISSUE THREAD

**Issue by higuoxing** [wurahara/SEU-Beamer-Slide#4]
我很喜欢这个项目，但是在新机器安装 TeX 编译器很烦，可能成为了大家使用这个项目的障碍。为了方便大家使用，维护者可以考虑发布到 overleaf，这样可以在线编译。我把发布到 overleaf 步骤发到这里，如果维护者有空的话可以考虑发布一下，并在 README 提及一下 :-)

1. 注册/登录 [overleaf](https://www.overleaf.com/)
2. 切换到 [Projects 页面](https://www.overleaf.com/project)
3. 点击 Upload Project （Import from GitHub 是收费项目 😭） 上传 [zip 包](https://github.com/TouchFishPioneer/SEU-Beamer-Slide/archive/master.zip)
![image](https://user-images.githubusercontent.com/21099318/106440998-78e38680-64b4-11eb-88b3-cf9f22c7b849.png)
4. 点击左上角 Menu 切换编译器到 XeLaTeX
![image](https://user-images.githubusercontent.com/21099318/106441972-b09efe00-64b5-11eb-897d-eb9868bc0f1e.png)
5. 点击 Submit 提交到 overleaf gallery，这样大家就可以直接点击链接使用模板了
![image](https://user-images.githubusercontent.com/21099318/106442876-cbbe3d80-64b6-11eb-9833-7848c9950b10.png)

**Comment by wurahara** [comment]
Since the overleaf link has been uploaded by @haoruilee, this issue would be closed.

Again, @haoruilee, thanks for your work and kindness.
