### ISSUE TITLE
frametitle 的最右侧 margin 有空白，请问设置哪个参数？

### ISSUE THREAD

**Issue by sli1989** [wurahara/SEU-Beamer-Slide#6]
谢谢

**Comment by higuoxing** [comment]
在 PR #7 中修复了 ...

**Comment by wurahara** [comment]
Thanks for your kindly report and revision. @higuoxing

**Comment by higuoxing** [comment]
> Thanks for your kindly report and revision. @higuoxing

My pleasure :-) Can I join this org so that I can help maintain this project?

**Comment by wurahara** [comment]
> > Thanks for your kindly report and revision. @higuoxing
> 
> My pleasure :-) Can I join this org so that I can help maintain this project?

I have added you into the maintain list of this repo, you can check your email and get the invite link.
